CREATE ROLE rol_comercial;
GRANT SELECT ON JARDINERIA.CLIENTES TO rol_comercial;
GRANT SELECT ON JARDINERIA.PRODUCTOS TO rol_comercial;
GRANT SELECT ON JARDINERIA.PEDIDOS TO rol_comercial;
GRANT INSERT ON JARDINERIA.PEDIDOS TO rol_comercial;
GRANT INSERT ON JARDINERIA.PAGOS TO rol_comercial;



