CREATE OR REPLACE VIEW v_resumen_clientes AS
SELECT
  c.CODIGOCLIENTE,
  c.NOMBRECLIENTE,
  COUNT(DISTINCT p.CODIGOPEDIDO) AS pedidos_realizados,
  COALESCE(SUM(dp.CANTIDAD), 0) AS unidades_compradas
FROM CLIENTES c
LEFT JOIN PEDIDOS p ON c.CODIGOCLIENTE = p.CODIGOCLIENTE
LEFT JOIN DETALLEPEDIDOS dp ON p.CODIGOPEDIDO = dp.CODIGOPEDIDO
GROUP BY c.CODIGOCLIENTE, c.NOMBRECLIENTE;
