CREATE OR REPLACE VIEW v_clientes_con_pagos AS
SELECT 
  c.CODIGOCLIENTE,
  c.NOMBRECLIENTE,
  COALESCE(SUM(p.CANTIDAD), 0) AS total_pagado
FROM CLIENTES c
LEFT JOIN PAGOS p ON c.CODIGOCLIENTE = p.CODIGOCLIENTE
GROUP BY c.CODIGOCLIENTE, c.NOMBRECLIENTE;



