CREATE OR REPLACE VIEW v_productos_ventas AS
SELECT
  p.CODIGOPRODUCTO,
  p.NOMBRE,
  SUM(dp.CANTIDAD) AS unidades_vendidas,
  SUM(dp.CANTIDAD * dp.PRECIOUNIDAD) AS importe_total
FROM PRODUCTOS p
JOIN DETALLEPEDIDOS dp ON p.CODIGOPRODUCTO = dp.CODIGOPRODUCTO
GROUP BY p.CODIGOPRODUCTO, p.NOMBRE;

