CREATE OR REPLACE VIEW v_pedidos_pendientes AS
SELECT
  p.CODIGOPEDIDO,
  c.NOMBRECLIENTE,
  p.FECHAPEDIDO,
  p.ESTADO AS estado_actual
FROM PEDIDOS p
JOIN CLIENTES c ON p.CODIGOCLIENTE = c.CODIGOCLIENTE
WHERE (LOWER(p.ESTADO) <> 'entregado' OR p.FECHAENTREGA IS NULL);

